import localFont from "next/font/local";
import "./globals.css";
import { SearchContextProvider } from "./context/SearchContext";

const vazir = localFont({
  src: [
    {
      path: './fonts/Vazir-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/Vazir-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    
    {
      path: './fonts/Vazir-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Vazir-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-vazir',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SearchContextProvider>
    <html lang="fa" dir="rtl">
      <body
        className={vazir.variable}
      >
        
        {children}
      </body>
    </html>
    </SearchContextProvider>
  );
}
